// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function ExecuteRequestSimple(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteRequestSimple'](arg1, arg2, arg3, arg4);
}

export function ExecuteRequestWithTimeout(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteRequestWithTimeout'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportCollection(arg1) {
  return window['go']['main']['App']['ExportCollection'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportCollection(arg1) {
  return window['go']['main']['App']['ImportCollection'](arg1);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function SaveRequest(arg1, arg2) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2);
}
