// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function ExecuteRequestSimple(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteRequestSimple'](arg1, arg2, arg3, arg4);
}

export function ExecuteRequestWithTimeout(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteRequestWithTimeout'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
