// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {response} from '../models';

export function ExecuteRequest(arg1:main.RequestParams):Promise<response.ResponseData>;

export function ExecuteRequestSimple(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<response.ResponseData>;

export function ExecuteRequestWithTimeout(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:number):Promise<response.ResponseData>;

export function Greet(arg1:string):Promise<string>;
