// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {response} from '../models';
import {collection} from '../models';

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function ExecuteRequest(arg1:main.RequestParams):Promise<response.ResponseData>;

export function ExecuteRequestSimple(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<response.ResponseData>;

export function ExecuteRequestWithTimeout(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:number):Promise<response.ResponseData>;

export function ExportCollection(arg1:string):Promise<string>;

export function GetCollection(arg1:string):Promise<collection.Collection>;

export function Greet(arg1:string):Promise<string>;

export function ImportCollection(arg1:string):Promise<void>;

export function ListCollections():Promise<Array<string>>;

export function SaveRequest(arg1:string,arg2:collection.SavedRequest):Promise<void>;
