// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {assertion} from '../models';
import {main} from '../models';
import {collection} from '../models';
import {environment} from '../models';

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function EvaluateAssertions(arg1:response.ResponseData,arg2:Array<assertion.Rule>):Promise<Array<assertion.Result>>;

export function ExecuteRequest(arg1:main.RequestParams):Promise<response.ResponseData>;

export function ExecuteRequestSimple(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<response.ResponseData>;

export function ExecuteRequestWithTimeout(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:number):Promise<response.ResponseData>;

export function ExportCollection(arg1:string):Promise<string>;

export function GetCollection(arg1:string):Promise<collection.Collection>;

export function GetEnvironment(arg1:string):Promise<environment.Environment>;

export function Greet(arg1:string):Promise<string>;

export function ImportCollection(arg1:string):Promise<void>;

export function ImportOpenAPI(arg1:string,arg2:string):Promise<number>;

export function ListCollections():Promise<Array<string>>;

export function ListEnvironments():Promise<Array<string>>;

export function SaveEnvironment(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SaveRequest(arg1:string,arg2:collection.SavedRequest):Promise<void>;
